### ISSUE TITLE
Page creation Analysis Platforms

### ISSUE THREAD

**Issue by SophieMacadamia** [valeriupredoi/valeriupredoi.github.io#14]
Hi Vi, 
Can you please create a page that would be called "sdm-analysis-platforms-service" ? 
In "How to Access and Use Model Data?">>"Climate Analytics Service" page, there is the following text near the beginning: 
Important note: unfortunately we cannot offer unlimited resources. The ECAS only provides computer resources for pre- and post-processing (not suitable for simulation runs) in shared computing nodes. If you would like to use exclusive extensive resources, please apply to our Analysis Platforms service.

I want the three last words, "Analysis Platforms service", to lead to the newly created page. It is a page where I will copy paste the content of this page: https://portal.enes.org/data/data-metadata-service/analysis-platforms 

Thanks !

**Comment by valeriupredoi** [comment]
@SophieMacadamia done!

For future work, you can use the empty template in `pages` for a new page:

```
cp pages/empty-template.md pages/your-new-page.md
```

and edit the new page by changing titles etc. Of course I can do this for you anytime, but just in case I'm not able to get to it fast enough :grin: 

Here's the page: https://valeriupredoi.github.io/sdm-analysis-platforms-service/ linking from https://valeriupredoi.github.io/sdm-climate-analytics-data/

:beaver:

**Comment by valeriupredoi** [comment]
closing this, should work now :grin:
