### ISSUE TITLE
Adding links and PDF documents to various sections 

### ISSUE THREAD

**Issue by valeriupredoi** [valeriupredoi/valeriupredoi.github.io#7]
@SophieMacadamia was kind and nice to start working on this :smiley: 

Sophie, pls ping me here when you done one section so I can come and either add the roots to files or fix anything if needs fixing, or ask anything here :beer:

**Comment by SophieMacadamia** [comment]
Ok thanks, adding the links and .pdf files to deliverables now ! 
One just tiny problem i encounter when I do "git diff": it shows me the changes done but it does not automatically put the "sophie@sophie-Virtualbox:-/valeriupredoi.github.io" line necessary to do any other command. it says [END] and i cannot do anything. The only way i found to have it appear again was to do "ctrl + Z", which writes "Stopped git diff" but makes the command line appear again for me. I don't think it has any consequences anyway on my actions (i am able to do the commit and push then)

**Comment by valeriupredoi** [comment]
not at all, `git diff` gets you in some bespoke git text editor, you can get out of it with Ctrl+C, Ctrl+Z, Esc (escape), q (the key q) - don't worry about it :) Thanks lots, Sophie!

**Comment by SophieMacadamia** [comment]
Great ! Just to let you know that I am done uploading all the deliverables/milestones on the GitHub repo and wrote their names in () after their associated deliverable/milestone ! Hope this helps, let me know you'll need me to do next ! :-)

**Comment by valeriupredoi** [comment]
excellent work @SophieMacadamia :beer: 

A few points: there are a couple files missing in [Deliverables](https://valeriupredoi.github.io/deliverables/):

- IS-ENES_D5.4_ESGF_involvement.pdf
- IS-ENES3_D7.3.pdf
- IS-ENES3_D9.3.pdf

Could you pls add them and link them correctly too? The root to be added in front of the file is `https://raw.githubusercontent.com/valeriupredoi/valeriupredoi.github.io/master/pdf_documents/` so if you add that to eg `IS-ENES_D5.4_ESGF_involvement.pdf` that should look like `https://raw.githubusercontent.com/valeriupredoi/valeriupredoi.github.io/master/pdf_documents/IS-ENES_D5.4_ESGF_involvement.pdf`

Also, after this, could you pls go through the [Milestones](https://valeriupredoi.github.io/milestones/) and add the roots to files, and then check each link works?

One last thing - I have formatted the links in [Presentations](https://valeriupredoi.github.io/presentations-posters/) for you to just add the links in the [MD file](https://github.com/valeriupredoi/valeriupredoi.github.io/blob/master/pages/presentations-posters.md) - see which ones are missing (quite a few are) and if you could add them, that would be absolutely legend :superhero: Cheers muchly!!

**Comment by valeriupredoi** [comment]
Oh and I forgot - files should not have spaces in their names - those break linking, it's best if you replace spaces in filenames with either dashes `-` or underscores `_` :+1:

**Comment by valeriupredoi** [comment]
Here is a pro tip that'll improve the user-friendliness of your work on such files - see this file for example https://github.com/valeriupredoi/valeriupredoi.github.io/blob/master/pages/presentations-posters.md - if you want to edit it - you can do it straight into the GitHub editor: go to the little pencil on the right upper bar (between "Blame" and trash bin) and click on it - you can edit the file straight into the editor (add links, copy-paste stuff etc), then commit straight on GitHub (you can use your Windows window for better, bigger window) :grinning:

**Comment by SophieMacadamia** [comment]
I've tried to add roots for all the milestones, but it says Error 404 when I try to dowload any one of them, even after it has finished building... Yet the roots are here (I copy-paste what you sent). My terminal also recognises that the roots have been added. Can you have a look to see where the problem come from ? 

I wonder whether this comes from the fact that my URL in the Github pdf document markdown, I have the following URL: https://github.com/valeriupredoi/valeriupredoi.github.io/tree/master/pdf_documents , with "tree", which does not appear on the root you gave me above (but maybe this is normal) ?

**Comment by valeriupredoi** [comment]
no worries @SophieMacadamia - the root is correct as it should be - it's just that the files don't have the `.pdf` extension - every file must have its correct extension (whether it be jpg, txt, pdf etc) so that the loader can recognize it :grin:

**Comment by valeriupredoi** [comment]
BTW the root you are talking about `https://github.com/valeriupredoi/valeriupredoi.github.io/tree/master/pdf_documents` is for the file in view mode in HTML, what you need the the one that starts with `raw` because that is the one that loads the file when a user clicks on it - you get that if you press the Download button after you accessed the file in GitHub :+1:

**Comment by SophieMacadamia** [comment]
Ahhhh I see, how simple was that... I'll add the .pdf then. And ok, I understand for the Raw !

**Comment by valeriupredoi** [comment]
no worries for Milestones, I just added the extensions - for the future file additions :smile:

**Comment by valeriupredoi** [comment]
OK I fixed all the broken filenames in **Deliverables** (and checked) and **Milestones** (and checked) -> those should be done now wohoo :tada: @SophieMacadamia could you pls go through Presentations and Posters and do the same (add files and their full links in the MD file)? Then we are pretty much done with that whole section :+1: We'll have to have a look at Lectures etc and then that's totally done!

**Comment by SophieMacadamia** [comment]
Thanks for fixing the .pdf. For the presentations/poster, we still need to change the looks of the page before I add the links. 
I have the following idea: 
- Have the "IS-ENES3 Workshops" (those with the "internal links") in a table (as for EGus), but as the first one to appear on the page, before all the EGUs, AGUs...
- Have the last table "Other" (with the reminaing events), BUT to write the title of the presentation instead of the event name, and in front of each of these presentation titles, their associated event (instead of writing "Link" or "File", we write the event instead). 
But we can discuss it this afternoon for our telco, not certain it is very clear right now. I would be keen on trying to change that section actually.

Also, for the last section "Lectures, Webinars, Tutorials", there are six playlists (= six webinars) on the project YouTube channel: https://www.youtube.com/channel/UC24YCohRVh1WXqzBm9tkL2g/playlists
Maybe we can have them embedded ? Or listed, with a picture for each playlists. We can discuss that as well at our telco !

**Comment by SophieMacadamia** [comment]
Valeriu, I have the thumbnails for the YouTube videos, do you want me to download them in the images.md repository or do you want me to send them to you by email ? The first option I guess. 

I put here the pictures name and its associated playlist:
- Climate_Impact_School: https://www.youtube.com/watch?v=_42ltTQzY30&list=PLFvev1W5vG7NDEZhxObXDd1Bc5rnBpYrk
- Training_ECAS: https://www.youtube.com/watch?v=deQUK9k47uo&list=PLFvev1W5vG7P1VGITP3ys1GpXnhL--jIc
- ML-AI_workshop: https://www.youtube.com/watch?v=P0RtRdLvAGA&list=PLFvev1W5vG7NP2xSRRorQabHWKKwJqw54
- Coupling_Workshop: https://www.youtube.com/watch?v=p5kQii_UNlU&list=PLFvev1W5vG7O-h0H1AYrXHtkPQ3zAOZjt
- CORDEX_and_CMIP: https://www.youtube.com/watch?v=SSjod5McTZo&list=PLFvev1W5vG7Nv-wzntcCp46XbqJKWaqRB
- Compute_and_analytics: https://www.youtube.com/watch?v=Kr9IIa4JL08&list=PLFvev1W5vG7N69d4mD0Aa6FgNiuisQDcl

**Comment by valeriupredoi** [comment]
cool, cheers @SophieMacadamia - I will add them to the page, if you could dump the images in the Images folder and tell me what they're called it'd be great :+1:

**Comment by SophieMacadamia** [comment]
Done, uploaded in images. Their names are what I described in my comment above (Climate_Impact_School, etc...)

**Comment by valeriupredoi** [comment]
excellent, thanky much, Sophi!

**Comment by valeriupredoi** [comment]
OK @SophieMacadamia - those Current/Past issued items are now fixed nicely:
- access calls: https://valeriupredoi.github.io/access-calls/ (thats complete too, no need to add more)
- workshops: https://valeriupredoi.github.io/workshops/ (this needs lots of past workshops added - could you maybe get started on that? No worries if there are formatting/style issues - I can fix those)
- training: https://valeriupredoi.github.io/training/ (again - lots of past training events still need to be added)

Gonna go about the video page now :grin:

**Comment by valeriupredoi** [comment]
video page done with 6 nice clickable widgets that each takes you to the YT playlist https://valeriupredoi.github.io/lectures-tutorials-webinars/ :grin:

**Comment by SophieMacadamia** [comment]
Super nice, I love it ! :-D
Btw do you have Slack ? We have an IS-ENES3 Slack and I had the thought that the "drawing" tool available when sharing your screen on Slack could be useful for us !

**Comment by SophieMacadamia** [comment]
I will try to add some events now
(well, add links to the existing events already for those missing)

**Comment by valeriupredoi** [comment]
> Super nice, I love it ! :-D Btw do you have Slack ? We have an IS-ENES3 Slack and I had the thought that the "drawing" tool available when sharing your screen on Slack could be useful for us !

haha cheers :grin: - I have actually just improved it - the images are now with the same size so the entries are not jittered about - OCD much :laughing: 

I do have Slack - my user is `valeriu.predoi` - maybe you can add me to the IS-ENES3 channel or we can just chat there for clarifications? I'd still stick to here for actions and progress - goo to have Fanny and others see the discussion :+1:

**Comment by valeriupredoi** [comment]
> I will try to add some events now (well, add links to the existing events already for those missing)

awesome, cheers muchly, Sophie!

**Comment by SophieMacadamia** [comment]
Soooo.... Some problems regarding the event I tried adding (Eastern European climate indices workshop):
- The picture work (I did not put the one I wanted tho), BUT it is super huge ! How can I reduce it ? I guess it comes from the file source ? 
- The table are ok, but they have two equals columns: how do I put one column larger than the other one (in this case, the first column sould be longer than the second one) ?

**Comment by valeriupredoi** [comment]
I think we can close this too since you've plugged almost all the links by now, and all is good and checked as well - excellent work @SophieMacadamia :partying_face:
