### ISSUE TITLE
Presentations and Posters sub-section

### ISSUE THREAD

**Issue by valeriupredoi** [valeriupredoi/valeriupredoi.github.io#8]
@SophieMacadamia I have changed a bit the organization of [Presentations and Posters](https://valeriupredoi.github.io/presentations-posters/) subsection - it's still not 100% clear to me how you wanted the structuring of various conferences and internal meetings to appear here - my apologies, but could you please explain to me how you want it to appear? Note that the links to various IS-ENES3 Meetings are now pointing to the Workshops' entries - so that I got it right - but further on it's the question how it should be :smiley:

**Comment by SophieMacadamia** [comment]
Awesome for the IS-ENES3 Meetings table ! (One tiny detail, IS-ENES3 Workshops would be better, but that's a detail that can be changed later). My main request would be to move that table right below the summary table at the top of the page (right before the AGU2019 one), in order to have it as No.1
Does it makes sense ?

**Comment by SophieMacadamia** [comment]
For the "Other table", it is very good, I will just modify the titles: I will add the title of the presentation within the title (for now it is just the title of the event during which the presentation was delivered), so I will add that.

**Comment by valeriupredoi** [comment]
ahaa sure, got it! - makes sense, will do that now, cheers for babysitting me :+1:

**Comment by valeriupredoi** [comment]
how do you like it now: https://valeriupredoi.github.io/presentations-posters/ ?

**Comment by valeriupredoi** [comment]
OK now the section should be done https://valeriupredoi.github.io/presentations-posters/ - all links working, and structure re-shuffled - they point to some workshops that have only titles (no content) on the Workshops page but adding content to those will happen there, IMHO Presentations and Posters should be done now, what you reckon @SophieMacadamia :wine_glass:

**Comment by valeriupredoi** [comment]
closing this since I think it's all good now, feel free to reopen @SophieMacadamia :+1:
