### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by SophieMacadamia** [valeriupredoi/valeriupredoi.github.io#9]
For the Archive section, the pictures of the widgets IS-ENES3 Phase 1 and IS-ENES3 Pahse 2 are in the .images folder:
- Phase 1: [Photo_IS-ENES_GA1_Barcelone_2010_0526.JPG](https://github.com/valeriupredoi/valeriupredoi.github.io/blob/master/images/Photo_IS-ENES_GA1_Barcelone_2010_0526.JPG) 
- Phase 2: [Photo_IS-ENES2_GA3_Paris_2017_0117.JPG](https://github.com/valeriupredoi/valeriupredoi.github.io/blob/master/images/Photo_IS-ENES2_GA3_Paris_2017_0117.JPG)

Thanks :-)

**Comment by valeriupredoi** [comment]
you did a great job opening the issue (which I missed haha) and actually plugging those photos in yourself :tada:
